---
apiVersion: v1
kind: Service
metadata:
  name: pong-svc
spec:
  type: ClusterIP
  selector:
    app: pongapp
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
---

apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
spec: 
  selector:
    app: pongapp
  ports:
  - name: http
    port: 3001
    targetPort: 3000

