apiVersion: apps/v1
kind: Deployment
metadata:
  name: projectv01
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projectv01
  template:
    metadata:
      labels:
        app: projectv01
    spec:
      containers:
        - name: projectv01
          image: siddarthal/projectv01:latest