name: your-app-name CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "your-app-name/src/App.js"
      - "your-app-name/Dockerfile"
      - "your-app-name/package.json"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
      - name: logging in to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
            context: your-app-name
            push: true
            tags: siddarthal/reactapp:latest



