name: todobackend CI/CD

on:
  push:
    branches:
      - master
    paths:
      - "todobackend/index.js"
      - "todobackend/Dockerfile"
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
      - name: logging in to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and push
        uses: docker/build-push-action@v5
        with:
            context: todobackend
            push: true
            tags: siddarthal/todobackend:latest



